### ISSUE TITLE
 Tokenizer class GemmaTokenizer does not exist or is not currently imported.

### ISSUE THREAD

**Issue by cheezecrisp** [kijai/ComfyUI-LuminaWrapper#1]
Already downloaded the gemma models to the path 'ComfyUI\models\LLM\gemma-2b'
And also inputed my huggingface token into the node 'DownloadAndLoadGemmaModel' in workflow
But got following error:

!!! Exception during processing!!! Tokenizer class GemmaTokenizer does not exist or is not currently imported.
Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LuminaWrapper\nodes.py", line 111, in loadmodel
    tokenizer = AutoTokenizer.from_pretrained(gemma_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\models\auto\tokenization_auto.py", line 811, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class GemmaTokenizer does not exist or is not currently imported.

Prompt executed in 0.00 seconds

**Comment by kijai** [comment]
I'm not sure, but I think this could mean your transformers version needs to be updated.

**Comment by zhuole1025** [comment]
Yes, update your transformer will solve this issue

**Comment by cheezecrisp** [comment]
> I'm not sure, but I think this could mean your transformers version needs to be updated.

Thank you! It's OK now.

**Comment by cheezecrisp** [comment]
Solved
