### ISSUE TITLE
Error while deserializing header: HeaderTooLarge 

### ISSUE THREAD

**Issue by thinkingjimmy** [kijai/ComfyUI-LuminaWrapper#21]
When I run this "lumina_next_t2i_composition_example_01.json" template.

ComfyUI showed this error:

```
!!! Exception during processing!!! Error while deserializing header: HeaderTooLarge
Traceback (most recent call last):
  File "/comfyui/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/comfyui/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/comfyui/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/comfyui/nodes.py", line 689, in load_vae
    sd = comfy.utils.load_torch_file(vae_path)
  File "/comfyui/comfy/utils.py", line 14, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
  File "/usr/local/lib/python3.10/site-packages/safetensors/torch.py", line 311, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
```

**Comment by kijai** [comment]
This would indicate that the model file is corrupt, maybe unfinished download?

**Comment by thinkingjimmy** [comment]
Thanks for the reply, that is indeed the problem. My VAE didn't download properly.
